[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
postgres = "0.19.2"

[lib]
name = "rust-api"
path = "src/lib.rs"

[[bin]]
name = "rust-api"
path = "src/main.rs"
